---

 - name: Install logrotate
   package:
     name: logrotate
     state: present

 - name: Install xz-utils
   package:
     name: xz-utils
     state: present

 - name: Compress logs with XZ
   blockinfile:
     dest: /etc/logrotate.conf
     block: |
      dateext
      compress
      compresscmd /usr/bin/xz
      uncompresscmd /usr/bin/unxz
      compressext .xz

 - name: Keep 108 instead of 4 weeks of backlog
   lineinfile:
     dest: /etc/logrotate.conf
     regexp: "^rotate "
     line: rotate 108

 - name: Keep 108 instead of 4 weeks of backlog for rsyslog
   lineinfile:
     dest: /etc/logrotate.d/rsyslog
     regexp: "\\s*rotate "
     line: "\trotate 108"
     insertafter: "^{$"
